MyEnquiry/Controllers/DoneCasesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyEnquiry_BussniessLayer.Helper;
using MyEnquiry_BussniessLayer.Interface;
using MyEnquiry_DataLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyEnquiry.Controllers
{
    [Authorize]
    public class DoneCasesController : Controller
    {
        private ICases _case;


        public DoneCasesController(ICases casemodel)
        {
            _case = casemodel;

        }
        public IActionResult Index()
        {

            return View();
        }



        public IActionResult Display()
        {

            var result = _case.GetDoneCases(ModelState,this.User);
            if (!ModelState.IsValid)
            {
                return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
            }
            return PartialView("_Display", result);
        }


        public async Task<IActionResult> GetPDF(int Id)
        {
            try
            {

                var result = await _case.GetPDF(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }

                return File(result, System.Net.Mime.MediaTypeNames.Application.Octet, "Case"+Id + ".pdf");

                


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }
        public async Task<IActionResult> ChangeStatus(int Id,int type, string reson="")
        {
            try
            {

                var result = await _case.ChangeStatus(ModelState, Id,type, reson);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }

                return Json(result);

                


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }




        public IActionResult OpenRejectModal(int Id)
        {
            ViewBag.Id = Id;

            return PartialView("_RejectCase");
        }



    }
}

MyEnquiry/Views/DoneCases/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MyEnquiry_BussniessLayer.ViewModel
@{
    ViewData["Title"] = "الحالات المنتهية";

    Layout = "~/Pages/Shared/_Layout.cshtml";

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/select2.css">

<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">



        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">

                            <strong class="card-title">الحالات المنتهية</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispaly">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>
<div class="disfiles"></div>


@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

    <script src="~/js/cutompages/DoneCases.js"></script>


}

MyEnquiry/Views/DoneCases/_Display.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ICollection<MyEnquiry_DataLayer.Models.Cases>

@using MyEnquiry.Helper
<table class="table datatables" id="dataTable-1">
    <thead>
        <tr>
            <th>رقم الحالة</th>
            <th>اسم العميل</th>
            <th>رقم العميل</th>
            <th>نوع الحالة</th>
            <th>اسم الشركة</th>
            <th>تحميل الملف</th>
            <th>موافقة</th>
            <th>رفض</th>
           
            
           
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>


            <td>@item.Id</td>
            <td>@item.ClientName</td>
            <td>@item.ClientNumbers</td>
            <td>@(item.CaseType!=null?item.CaseType.NameAr:"غير معروف")</td>
            <td>@(item.Company!=null?item.Company.NameAr:"غير معروف")</td>
            
            <td><a  href="@item.FilesANswer" download> تحميل  PDF</a></td>


            <td>
                @if (item.CaseStatus.Id == (int)CaseEnumStatus.AcceptedFromBank)
                {



                    <label class="alert alert-success">تم قبول الحالة</label>

                }
                else if (item.CaseStatus.Id < (int)CaseEnumStatus.AcceptedFromBank)
                {
                    <button type="button" data-id="@item.Id" data-type="1" class="btn mb-2 btn-outline-success accept">قبول</button>
                }



            </td>

            <td>
                @if (item.CaseStatus.Id == (int)CaseEnumStatus.AcceptedFromBank)
                {



                    <label class="alert alert-success">تم قبول الحالة</label>

                }
                else if (item.CaseStatus.Id < (int)CaseEnumStatus.AcceptedFromBank)
                {
                    <button type="button" data-id="@item.Id" data-type="2" class="btn mb-2 btn-outline-danger reject">رفض</button>
                }



            </td>


        </tr>
        }



    </tbody>
</table>

MyEnquiry/Views/DoneCases/_RejectCase.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MyEnquiry_BussniessLayer.ViewModel

@{
    var id = (int)ViewBag.Id;

}
<!-- Modal -->
<div class="modal fade" id="SendCaseModal" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">ارجاع الحالة</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("ChangeStatus", "DoneCases", new { area = "" }, FormMethod.Post, true, new { @id = "formsend" }))
            {
                @Html.Hidden("Id", id)
                @Html.Hidden("type", 2)
                <div class="modal-body">

                    <div class="form-row">

                        <div class="form-group col-md-12  ">
                            <label for="simple-select2"></label>
                            @Html.TextArea("reson", "", new { @class = "form-control req", @type = "text", @placeholder = "برجاء كتابة سبب الرفض" })

                        </div>

                    </div>


                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            }
        </div>
    </div>
</div>