MyEnquiry/Controllers/ForgetController.cs
using Microsoft.AspNetCore.Mvc;
using MyEnquiry_BussniessLayer.Helper;
using MyEnquiry_BussniessLayer.Interface;
using System;
using System.Threading.Tasks;

namespace MyEnquiry.Controllers
{
    public class ForgetController : Controller
    {
        private IForgetPassword _IForgetPassword;
        public ForgetController(IForgetPassword IForgetPassword)
        {
            _IForgetPassword = IForgetPassword;

        }
        public IActionResult ForgetPassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SendCode(string Phone)
        {
            try
            {
                var code =await _IForgetPassword.SendCode(ModelState, Phone);
                if (code == null)
                {
                    return RedirectToAction(nameof(ForgetPassword));
                }
                else
                {
                    return RedirectToAction(nameof(Verifiy),new { UserId= code } );

                }
            }
            catch(Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }

        }
        public IActionResult Verifiy(string UserId)
        {
            ViewBag.UserId = UserId;
            return View();
        } 
        [HttpPost]
        public async Task<IActionResult> Verifiy(string UserId,string code)
        {
            try
            {
                ViewBag.UserId = UserId;
                var verfy = await _IForgetPassword.Verify(ModelState, UserId, code);
                if (UserId == null)
                {
                    ModelState.AddModelError("Model", "هذا المستخدم أو الكود غير صحيح");
                    return View();
                }
                else
                {
                    if (verfy != null)
                    {
                        return RedirectToAction(nameof(NewPassword), new { UserId= verfy });
                    }
                    else
                    {
                        return RedirectToAction(nameof(Verifiy), new { UserId = verfy });

                    }
                }
            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }
          public IActionResult NewPassword(string UserId)
        {
            ViewBag.UserId = UserId;
            return View();
        }
        [HttpPost]
        public IActionResult NewPassword( string UserId, string Password, string ConfirmPassword)
        {
            ViewBag.UserId = UserId;
            try
            {
                var ChangePasswprd = _IForgetPassword.ChangePasswprd(ModelState, UserId, Password, ConfirmPassword);
                if (ChangePasswprd==null)
                {
                    ModelState.AddModelError("Model", "حدث خطأ ما");
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "User");

                }
            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }
    }
}

MyEnquiry/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyEnquiry_BussniessLayer.Helper;
using MyEnquiry_BussniessLayer.Interface;
using MyEnquiry_BussniessLayer.ViewModel;
using MyEnquiry_BussniessLayer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyEnquiry.Controllers
{
    public class UserController : Controller
    {


        private IRoles _role;
        private IUsers _user;


        public UserController(IRoles role, IUsers user)
        {
            _role = role;
            _user = user;

        }

        public IActionResult Index()
        {
            return View();
        }


        #region Roles
        [HttpGet]
        //[Authorize(PermissionItem.Roles)]
        public IActionResult Roles()
        {
            return View();
        }

        public IActionResult DisplayRoleGrid()
        {

            var result = _role.GetRoles(ModelState);
            return PartialView("_DisplayRoles", result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(RoleView model)
        {
            try
            {

                var result = await _role.AddRole(ModelState, model);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }

        }


        public dynamic GetRole(string Id)
        {
            try
            {

                var result = _role.GetRole(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return PartialView("_EditRole", result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(RoleView model)
        {
            try
            {

                var result = await _role.EditRole(ModelState, model);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }

        public async Task<IActionResult> DeleteRole(string Id)
        {
            try
            {

                var result = await _role.DeleteRole(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }


        #endregion


        #region Users
        [HttpGet]
        //[Authorize(PermissionItem.Roles)]
        public IActionResult CashIndex()
        {
            return View();
        }

        public IActionResult DisplayCashGrid()
        {

            var result = _user.GetUsersCash(ModelState);
            return PartialView("_DisplayCashs", result);
        }

        [HttpGet]
        //[Authorize(PermissionItem.Roles)]
        public IActionResult Users()
        {
            ViewBag.Roles = _role.GetRoles(ModelState);
            ViewBag.Banks = _user.GetBanks(ModelState);
            ViewBag.Companies = _user.GetCompanies(ModelState);
            return View();
        }

        public IActionResult DisplayUserGrid()
        {

            var result = _user.GetUsers(ModelState);
            return PartialView("_DisplayUsers", result);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(UserView model)
        {
            try
            {

                var result = await _user.AddUser(ModelState, model);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }

        [HttpGet]
        public dynamic Changepassword(string Id)
        {
            try
            {

                var result = _user.GetUser(ModelState, Id);

                

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return PartialView("_Changepassword");


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ForgetPassword model)
        {
            try
            {

               

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }
                var result = await _user.ChangePassword(ModelState, model);
                return Json(result);
            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }

        public dynamic GetUser(string Id)
        {
            try
            {

                var result = _user.GetUser(ModelState, Id);

                ViewBag.Roles = _role.GetRoles(ModelState);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return PartialView("_EditUser", result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(UserView model)
        {
            try
            {

                var result = await _user.EditUser(ModelState, model);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }

        public async Task<IActionResult> DeleteUser(string Id)
        {
            try
            {
                var result = await _user.DeleteUser(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }

        }

        #endregion



        #region Permissions

        public IActionResult PermissionsIndex()
        {
            ViewBag.Roles = _role.GetRoles(ModelState);
            return View();
        }


        [HttpGet]
        public IActionResult Permissions(string Id)
        {
            try
            {
                var result = _user.GetPermissionPages(ModelState, Id);


                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);
            }
            catch (Exception ex)
            {

                return CustomBadRequest.CustomExErrorResponse(ex);
            }
        }


        [HttpPost]
        public IActionResult PostPermissions(string[] Ids, string roleid)
        {
            try
            {
                var result = _user.PostPermissions(ModelState, Ids, roleid);


                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);
            }
            catch (Exception ex)
            {

                return CustomBadRequest.CustomExErrorResponse(ex);
            }
        }


        #endregion





        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }


        public async Task<ActionResult> Logout()
        {
            _user.SignUserOutAsync(ModelState);
            return RedirectToAction("Login", "User");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Login(LoginRq userModel)
        {
            try
            {
                var result = await _user.WebLoginUserAsync(ModelState, userModel);
                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }

                return Ok(new
                {
                    rout = Url.Action("HomeIndex", "Home")
                });

            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);
            }


        }

    }
}

MyEnquiry/Views/User/CashIndex.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MyEnquiry_BussniessLayer.ViewModel
@{
    ViewData["Title"] = "مستحقات المستخدمين";

    Layout = "~/Pages/Shared/_Layout.cshtml";

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/select2.css">

<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">



        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">

                            <strong class="card-title">المستحقات</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispaly">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>
<div class="disfiles"></div>


@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

    <script src="~/js/cutompages/Users.js"></script>


}

MyEnquiry/Views/User/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Pages/Shared/_LoginLayout.cshtml";

}
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
@using (Html.BeginForm("Login", "User", new { area = "" }, FormMethod.Post, true, new { @id = "LoginForm", @class = "col-lg-3 col-md-4 col-10 mx-auto text-center", @role = "form" }))
{
<a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="#">
    @*<svg version="1.1" id="logo" class="navbar-brand-img brand-md" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 120 120" xml:space="preserve">
    <g>
    <polygon class="st0" points="78,105 15,105 24,87 87,87 	" />
    <polygon class="st0" points="96,69 33,69 42,51 105,51 	" />
    <polygon class="st0" points="78,33 15,33 24,15 87,15 	" />
              </g>
            </svg>*@
    <img id="logo" class="navbar-brand-img brand-md" src="~/logo/Group54387.svg" />
</a>
    <h1 class="h6 mb-3">تسجيل الدخول</h1>
    <div class="form-group">
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="email" id="email" class="form-control form-control-lg req" placeholder="البريد الالكترونى" required="" autofocus="">
    </div>
    <div class="form-group">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="password" class="form-control form-control-lg req" placeholder="كلمة المرور" required="">
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">دخول</button>
    <p class="mt-5 mb-3 text-muted"> <a asp-action="ForgetPassword" asp-controller="Forget">?Do you Forget Password</a></p>
    <p class="mt-5 mb-3 text-muted">© 2022 All Rights Reserved. By <a href="http://www.fairsolutions-fsc.com/" target="_blank">Fair-solutions</a></p>





}


@section Scripts {
    <!-- Sweet alert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>
    <script src="~/js/cutompages/Login.js"></script>

}

MyEnquiry/Views/User/PermissionsIndex.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MyEnquiry_BussniessLayer.ViewModel
@{
    ViewData["Title"] = "الصلاحيات";

    Layout = "~/Pages/Shared/_Layout.cshtml";
    var roles = (List<RoleView>)ViewBag.Roles;


}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/select2.css">
<link href="~/css/jsTree/style.min.css" rel="stylesheet">
<style>
    .jstree-open > .jstree-anchor > .fa-folder:before {
        content: "\f07c";
    }

    .jstree-default .jstree-icon.none {
        width: 0;
    }
</style>

<div class="container-fluid">
    <div class="row justify-content-center">

        <div class="col-lg-12">

            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">إضافة الصلاحيات</strong>
                        </div>
                        <div class="card-body">
                            <div class="form-group ">
                                <label for="simple-select2">المجموعات</label>
                                <select name="RoleId" class="form-control select2 req RoleId" id="simple-select2" width="100">
                                    <option value="">اختر المجموعه</option>
                                    @foreach (var item in roles)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                </select>
                            </div> <!-- form-group -->

                            <div class="col-lg-12 displaytree">




                            </div>
                            <div class="m-5 text-center">
                                <button type="button" onclick="submitMe()" class="btn btn-primary">حفظ التغييرات</button>
                            </div>

                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>


    </div>
</div>


@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>
    <script src="~/js/jsTree/jstree.min.js"></script>

    <script src="~/js/cutompages/permissions.js"></script>


}

MyEnquiry/Views/User/Roles.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">

        <div class="col-lg-4">

            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">إضافة مجموعة</strong>
                        </div>
                        <div class="card-body">
                            
                                @using (Html.BeginForm("AddRole", "User", new { area = "" }, FormMethod.Post, true, new { @id = "formaddRole" }))
                                {

                                    <div class="form-group">
                                        <label for="inputAddress">اسم المجموعة</label>
                                        @Html.TextBox("Name", "", new { @class = "form-control req", @type = "text", @placeholder = "برجاء كتابة اسم المجموعة" })

                                    </div>

                                    <button type="submit" class="btn btn-primary">اضافة</button>
                                }


                           
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>


        <div class="col-lg-8">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">المجموعات</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispalygrid">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>

<div class="disedit">

</div>

@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

    <script src="~/js/cutompages/Roles.js"></script>


}

MyEnquiry/Views/User/_Changepassword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MyEnquiry_BussniessLayer.ViewModel
@using MyEnquiry_BussniessLayer.ViewModels

@{
    var roles = (List<RoleView>)ViewBag.Roles;
}
@model ForgetPassword
<!-- Modal -->
<div class="modal fade" id="ChangePasswordUserModal" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">تعديل المستخدم</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("ChangePassword", "User", new { area = "" }, FormMethod.Post, true, new { @id = "formaChangepasswordUser" }))
            {
                <div class="modal-body">

                    @Html.HiddenFor(m => m.Id)

                    <div class="form-group">
                        <label for="Email">الرقم السرى </label>
                        @Html.TextBoxFor(m=>m.Password, new { @class = "form-control reqE", @type = "Password", @placeholder = "برجاء كتابة الرقم السرى" })

                    </div>
                    <div class="form-group">
                        <label for="Phone">تأكيد الرقم السرى</label>
                        @Html.TextBoxFor(m=>m.confirmpassword, new { @class = "form-control reqE", @type = "Password", @placeholder = "برجاء تأكيد الرقم السرى" })

                    </div>
                    </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                    <button type="submit" class="btn btn-primary">حفظ التعديلات</button>
                </div>
            }
        </div>
    </div>
</div>

MyEnquiry/Views/User/_DisplayCashs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ICollection<MyEnquiry_DataLayer.Models.UserWallet>

@using MyEnquiry.Helper
<table class="table datatables" id="dataTable-1">
    <thead>
        <tr>
            <th>اسم المستخدم</th>
            <th>المستحق له</th>
            
            <th>دفع</th>
            
           
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.GroupBy(s=>s.UserId).ToList())
        {
        <tr>


            <td>@item.FirstOrDefault().User.FullName</td>
            <td>@item.Sum(s=>s.Amount)</td>



            <td>
         
                    <button type="button" data-id="@item.FirstOrDefault().User.Id" class="btn mb-2 btn-outline-primary">دفع</button>                
            </td>


        </tr>
        }



    </tbody>
</table>

MyEnquiry/Views/User/_DisplayRoles.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ICollection<MyEnquiry_BussniessLayer.ViewModel.RoleView>
<table class="table datatables" id="dataTable-1">
    <thead>
        <tr>
            <th>الاسم</th>

            <th>تعديل</th>
            <th>حذف</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.Name</td>

                <td>
                    <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-primary editrole">تعديل</button>

                </td>
                <td>
                    <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-danger deleterole">حذف</button>

                </td>
            </tr>
        }



    </tbody>
</table>

MyEnquiry/Views/User/_DisplayUsers.cshtml
@model ICollection<MyEnquiry_BussniessLayer.ViewModel.UserView>
<table class="table table-responsive datatables" id="dataTable-2">
    <thead>
        <tr>
            <th>الاسم</th>
            <th>البريد الالكترونى</th>
            <th>رقم الهاتف(الواتس)</th>
            <th>سعر الحاله</th>
            <th>إسم الشركه أو البنك</th>
            <th>تعديل الرقم السرى</th>
            <th>تعديل</th>
            <th>حذف</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.FullName</td>
                <td>@item.Email</td>
                <td>@item.Phone</td>
                <td>@item.Price</td>
                <td class="text-center">
                    @if (item.Usertype == 1)
                    {
                    <label class=" alert-info "> بنوك</label>
                    }
                    else if (item.Usertype == 2)
                    {
                <label class="alert-warning" style="background-color:lightgray;"> شركات</label>
                    }
                    else
                    {
                        <label class="alert-success" style="background-color:firebrick; color: white;">مسؤول</label>
                    }


                </td>

                <td>
                    <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-primary changepass">تغير الباسورد</button>

                </td> 
                <td>
                    <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-primary edituser">تعديل</button>

                </td>
                <td>
                    <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-danger deleteuser">حذف</button>

                </td>
            </tr>
        }
        
    </tbody>
</table>

MyEnquiry/Views/User/_EditRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MyEnquiry_BussniessLayer.ViewModel.RoleView
<!-- Modal -->
<div class="modal fade"  id="EditRoleModal" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">تعديل المجموعة</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("EditRole", "User", new { area = "" }, FormMethod.Post, true, new { @id = "formaEditRole" }))
            {
                <div class="modal-body">

                    @Html.HiddenFor(m=>m.Id)
                    <div class="form-group">
                        <label for="inputAddress">اسم المجموعة</label>
                        @Html.TextBoxFor(m=>m.Name, new { @class = "form-control reqE", @type = "text", @placeholder = "برجاء كتابة اسم المجموعة" })

                    </div>
            

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                    <button type="submit" class="btn btn-primary">حفظ التعديلات</button>
                </div>
            }
        </div>
    </div>
</div>