MyEnquiry/Controllers/BankCompanyCaseController.cs
using Microsoft.AspNetCore.Mvc;
using MyEnquiry_BussniessLayer.Helper;
using MyEnquiry_BussniessLayer.Interface;
using MyEnquiry_BussniessLayer.ViewModels;
using MyEnquiry_DataLayer.Models;
using System;
using System.Threading.Tasks;

namespace MyEnquiry.Controllers
{
    public class BankCompanyCaseController : Controller
    {

        private IBankCompanyCase _bank;
        private IBankCases _bankq;


        public BankCompanyCaseController(IBankCompanyCase bank, IBankCases bankq)
        {
            _bank = bank;
            _bankq = bankq;
        }
        public IActionResult Index()
        {
            return View();
        }
  
        public IActionResult DisplayGrid()
        {

            var result = _bank.Get(ModelState, this.User);

            return PartialView("_DisplayBanks", result);
        }
        public IActionResult IndexBanc(int id)
        {
            ViewBag.id = id;
            ViewBag.Companies = _bank.GetCities(ModelState);

            ViewBag.CaseTypes = _bank.GetCaseTypes(ModelState);
            return View();
        }

        public IActionResult DisplayGridBanc(int id)
        {
            ViewBag.id = Convert.ToInt32(id);
            var result = _bank.GetBankCompany(ModelState, this.User, id);

            return PartialView("_DisplayBanks3", result);
        }

        public IActionResult CompanyIndex()
        {
            return View();
        }
  
        public IActionResult DisplayGridCompany()
        {

            var result = _bank.GetCompany(ModelState, this.User);

            return PartialView("_DisplayCompanyIndex", result);
        }  
        public IActionResult IndexBancCompany(int id)
        {
            ViewBag.id = id;
            ViewBag.Companies = _bank.GetCities(ModelState);
     
            ViewBag.CaseTypes = _bank.GetCaseTypes(ModelState);
            return View();
        }
  
        public IActionResult DisplayGridBancCompany(int id)
        {
            ViewBag.id = Convert.ToInt32(id);
           var result = _bank.GetAllCompany(ModelState, this.User,id);

            return PartialView("_DisplayBanksCompany3", result);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(BankCompanyVmAdd model)
        {
            try
            {

                var result = await _bank.Add(ModelState, model, this.User);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }
        [HttpGet]
        public dynamic GetbankCase(int Id)
        {
            try
            {

                var result = _bank.GetById(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }
                ViewBag.Companies = _bank.GetCities(ModelState);
                ViewBag.CaseTypes = _bank.GetCaseTypes(ModelState);

                return PartialView("_EditBankCase", result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BankCompanyVmAdd model)
        {
            try
            {

                var result = await _bank.Edit(ModelState, model,this.User);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }


        public async Task<IActionResult> Delete(int Id)
        {
            try
            {

                var result = await _bank.Delete(ModelState, Id);

                if (!ModelState.IsValid)
                {
                    return CustomBadRequest.CustomModelStateErrorResponse(ModelState);
                }


                return Json(result);


            }
            catch (Exception ex)
            {
                return CustomBadRequest.CustomExErrorResponse(ex);

            }


        }


    }
}

MyEnquiry/Views/BankCompanyCase/CompanyIndex.cshtml
  @{  Layout = "~/Pages/Shared/_Layout.cshtml";

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">

     

        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">البنوك</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispalygridmnb">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>

<div class="disedit">

</div>

@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

@*    <script src="~/js/cutompages/CompanyBank.js"></script>*@
    <script>
        function AllComapn() {
	$.ajax({
		url: "/BankCompanyCase/DisplayGridCompany",
		cache: false,
		success: function (html) {
			$(".dispalygridmnb").html(html);

			$('#dataTable-mnb').DataTable(
				{
					autoWidth: true,
					"lengthMenu": [
						[10, 20, 40, -1],
						[10, 20, 40, "All"]
					]
				});

		}
	});
}
$(document).ready(function () {

	AllComapn();


})



    </script>

}

MyEnquiry/Views/BankCompanyCase/Index.cshtml
  @{  Layout = "~/Pages/Shared/_Layout.cshtml";

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">

     

        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">الشركات</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispalygrid3">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>

<div class="disedit">

</div>

@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

    <script src="~/js/cutompages/CompanyBank.js"></script>


}

MyEnquiry/Views/BankCompanyCase/IndexBanc.cshtml
@using MyEnquiry_BussniessLayer.ViewModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    var Cities = (List<SelectView>)ViewBag.Companies;
    var casetypes = (List<SelectView>)ViewBag.CaseTypes;
    var igh = ViewBag.id;

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">
        
        <div class="col-lg-4">

            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">إضافة سعر</strong>
                        </div>
                        <div class="card-body">

                            @using (Html.BeginForm("Add", "BankCompanyCase", new { enctype = "multipart/form-data" }, FormMethod.Post, true, new { @id = "formaddbank" }))
                            {
                                <input hidden value="@(ViewBag.id)" name="CompaniesId" id="kjdk" data-id="@(ViewBag.id)">
                                      <div class="form-group col-md-12">
                                    <label for="simple-select2">أنواع الحالات</label>
                                    <select name="CaseTypesId" class="form-control select2 req" id="simple-select2" width="100">
                                        <option value="">اختر نوع الحالة</option>
                                        @foreach (var item in casetypes)
                                        {
                                            <option value="@item.Id">@item.Name</option>
                                        }
                                    </select>
                                </div>
                                      <div class="form-group col-md-12">
                                    <label for="simple-select2">المحافظه</label>
                                    <select name="CitiesId" class="form-control select2 req" id="simple-select2" width="100">
                                        <option value="">اختر المحافظه</option>
                                        @foreach (var item in Cities)
                                        {
                                            <option value="@item.Id">@item.Name</option>
                                        }
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="inputAddress"> سعر الحاله</label>
                                    @Html.TextBox("PriceCase", "", new { @class = "form-control req", @type = "text", @placeholder = "برجاء كتابة سعر الحاله" })
                                </div>
                             
                                <button type="submit" class="btn btn-primary">إضافه</button>
                            }



                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

        <div class="col-lg-8">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">التعاقد</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispalygrid">



                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>

<div class="disedit">

</div>

@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

    <script src="~/js/cutompages/CompanyBank.js"></script>


}

MyEnquiry/Views/BankCompanyCase/IndexBancCompany.cshtml
@using MyEnquiry_BussniessLayer.ViewModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    var Cities = (List<SelectView>)ViewBag.Companies;
    var casetypes = (List<SelectView>)ViewBag.CaseTypes;
    var igh = ViewBag.id;

}
<link href="~/css/sweetalert/sweetalert.css" rel="stylesheet">
<link rel="stylesheet" href="~/dark-rtl/css/dataTables.bootstrap4.css">

<div class="container-fluid">
    <div class="row justify-content-center">
     

        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <strong class="card-title">التعاقد</strong>
                        </div>
                        <div class="card-body">
                            <div class="dispalygridpas">
                                <input hidden value="@(ViewBag.id)" id="Adsd" />


                            </div>
                        </div> <!-- /. card-body -->
                    </div> <!-- /. card -->
                </div> <!-- /. col -->
            </div> <!-- /. end-section -->

        </div>

    </div>
</div>

<div class="disedit">

</div>

@section Scripts {


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
    <script src='~/dark-rtl/js/jquery.dataTables.min.js'></script>
    <script src='~/dark-rtl/js/dataTables.bootstrap4.min.js'></script>

    <script src="~/js/sweetalert/sweetalert.min.js"></script>

@*    <script src="~/js/cutompages/CompanyBank.js"></script>*@
<script>
    
function COmpanyById() {
	var id2 = $('#Adsd').val();
	$.ajax({
		url: "/BankCompanyCase/DisplayGridBancCompany",
		cache: false,
		data: { 'id': id2 },
		success: function (html) {
			$(".dispalygridpas").html(html);

			$('#dataTable-pas').DataTable(
				{
					autoWidth: true,
					"lengthMenu": [
						[10, 20, 40, -1],
						[10, 20, 40, "All"]
					]
				});

		}
	});
}
$(document).ready(function () {

	COmpanyById();


})
</script>

}

MyEnquiry/Views/BankCompanyCase/_DisplayBanks.cshtml
@model ICollection<MyEnquiry_DataLayer.Models.Companies>
<table class="table datatables" id="dataTable-2">
    <thead>
        <tr>
            
            <th>إسم الشركه</th>
            

            <th>إضافه</th>
           
        </tr>
    </thead>
    <tbody>
          @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>


                    <td>@item.NameAr</td>


                    <td>
                        <a href="~/BankCompanyCase/IndexBanc/@item.Id" data-Ukh="@item.Id"  class="btn mb-2 btn-outline-primary Newa">تسجيل الأسعار</a>

                    </td>

                </tr>
            }
        }


    </tbody>
</table>

MyEnquiry/Views/BankCompanyCase/_DisplayBanks3.cshtml
@model ICollection<MyEnquiry_BussniessLayer.ViewModels.BankCompanyVm>
<table class="table datatables" id="dataTable-1">
    <thead>
        <tr>
            
            <th>المحافظه</th>
            <th>نوع الحاله</th>
            <th>سعر الحاله</th>
      
            

            <th>تعديل</th>
            <th>حذف</th>
           
        </tr>
    </thead>
    <tbody>
          @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>


                    <td>@item.CaseTypesId</td>
                    <td>@item.CitiesId</td>
                    <td>@item.PriceCase</td>



                    <td>
                        <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-primary editbank">تعديل</button>

                    </td> 
                    <td>

                        <button type="button" data-id="@item.Id" class="btn mb-2 btn-outline-primary delete">حذف</button>

                    </td>

                </tr>
            }

        }

    </tbody>
</table>

MyEnquiry/Views/BankCompanyCase/_DisplayBanksCompany3.cshtml
@model ICollection<MyEnquiry_BussniessLayer.ViewModels.BankCompanyVm>
<table class="table datatables" id="dataTable-pas">
    <thead>
        <tr>
            
            <th>المحافظه</th>
            <th>نوع الحاله</th>
            <th>سعر الحاله</th>
      
            

        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>


                    <td>@item.CaseTypesId</td>
                    <td>@item.CitiesId</td>
                    <td>@item.PriceCase</td>





                </tr>
            }

        }

    </tbody>
</table>

MyEnquiry/Views/BankCompanyCase/_DisplayCompanyIndex.cshtml
@model ICollection<MyEnquiry_DataLayer.Models.Banks>
<table class="table datatables" id="dataTable-mnb">
    <thead>
        <tr>
            
            <th>إسم البنك</th>
            

            <th>إضافه</th>
           
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
          

            <td>@item.NameAr</td>
    

            <td>
                <a href="~/BankCompanyCase/IndexBancCompany/@item.Id" data-Ukh="@item.Id"  class="btn mb-2 btn-outline-primary Newa">التفاصيل</a>

            </td>
          
        </tr>
        }



    </tbody>
</table>

MyEnquiry/Views/BankCompanyCase/_EditBankCase.cshtml
@using MyEnquiry_BussniessLayer.ViewModel

@{
    var companies = (List<SelectView>)ViewBag.Companies;
    var casetypes = (List<SelectView>)ViewBag.CaseTypes;


}
@model MyEnquiry_DataLayer.Models.BankCompany
<!-- Modal -->
<div class="modal fade" id="EditBankCaseModal" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">تعديل الحالة من قبل البنك</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("Edit", "BankCompanyCase", new { area = "" }, FormMethod.Post, true, new { @id = "formaEdit" }))
            {
        <div class="modal-body">

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.CompaniesId)
            @Html.HiddenFor(m => m.BanksId)
            <div class="form-group ">
                <label for="CompanyId">أنواع الحالات</label>
                @Html.DropDownList("CaseTypesId", new SelectList(casetypes, "Id", "Name"), "اختر نوع الحاله", new { @class = "form-control select2 reqE", @id = "simple-select2" })


            </div>
            <div class="form-group ">
                <label for="CompanyId">المحافظات</label>
                @Html.DropDownList("CitiesId", new SelectList(companies, "Id", "Name"), "اختر الشركة", new { @class = "form-control select2 reqE", @id = "simple-select2" })
            </div>
             <div class="form-group">
              <label for="inputAddress"> سعر الحاله</label>
                @Html.TextBox("PriceCase", value:@Model.PriceCase, new { @class = "form-control reqE", @type = "text", @placeholder = "برجاء كتابة سعر الحاله"})
                    </div>

        </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                    <button type="submit" class="btn btn-primary">حفظ التعديلات</button>
                </div>
            }
        </div>
    </div>
</div>